### ISSUE TITLE
A new version needs to be created '0.9.5'

### ISSUE THREAD

**Issue by abdelkrimdev** [doublenot/refs#15]

**Comment by license2e** [comment]
Any particular reason why?

**Comment by abdelkrimdev** [comment]
Hi 🙂 
yes because the latest tag "0.9.4" is quite outdated compared to the latest commit
![image](https://user-images.githubusercontent.com/8070119/57147543-b555f000-6dbf-11e9-9248-605c2a154398.png)
VS
![image](https://user-images.githubusercontent.com/8070119/57147568-c7d02980-6dbf-11e9-85b7-5f8530bbe6db.png)

**Comment by license2e** [comment]
ah, good point! done, thanks!

**Comment by clemsos** [comment]
commenting on a close issue, but it relates as 0.9.5 hasn't been pushed to npm. Maybe can be added there too? Many thanks for the useful lib !

**Comment by license2e** [comment]
@clemsos Yeah, it seemed like the auto deploy feature wasn't working with TravisCI, but in trying to fix it, I had to increment the next publish version to `v0.9.7`

I apologize for any inconvenience... 

The good news is that the dependencies have also been updated, and now `npm audit` shouldn't complain anymore.

**Comment by clemsos** [comment]
all good, thank you very much !
